name: recipe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  firebase_auth: ^5.5.1
  provider: ^6.1.2
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.4.0
  record: ^5.2.1
  http: ^0.13.5
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/recipe_app.png
    - assets/stealth_image.png
    - assets/small_logo.png
    - assets/logo.png
