// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoAoSglA2UTx5XvJIZ_jjsVMZKtwvXdtw',
    appId: '1:525623252385:web:e7937d8301989cefb667e0',
    messagingSenderId: '525623252385',
    projectId: 'dishguise-cc6a0',
    authDomain: 'dishguise-cc6a0.firebaseapp.com',
    storageBucket: 'dishguise-cc6a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPDfJzKwa4BDLIcIjS3UnDdkafNmy5dSs',
    appId: '1:525623252385:android:ce4ddc923c51f313b667e0',
    messagingSenderId: '525623252385',
    projectId: 'dishguise-cc6a0',
    storageBucket: 'dishguise-cc6a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1T5GYuujUeG9AnR6LBMTRpBM5xOfQaig',
    appId: '1:525623252385:ios:5bb94450935260c7b667e0',
    messagingSenderId: '525623252385',
    projectId: 'dishguise-cc6a0',
    storageBucket: 'dishguise-cc6a0.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1T5GYuujUeG9AnR6LBMTRpBM5xOfQaig',
    appId: '1:525623252385:ios:5bb94450935260c7b667e0',
    messagingSenderId: '525623252385',
    projectId: 'dishguise-cc6a0',
    storageBucket: 'dishguise-cc6a0.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoAoSglA2UTx5XvJIZ_jjsVMZKtwvXdtw',
    appId: '1:525623252385:web:8e8fb3411ed6db07b667e0',
    messagingSenderId: '525623252385',
    projectId: 'dishguise-cc6a0',
    authDomain: 'dishguise-cc6a0.firebaseapp.com',
    storageBucket: 'dishguise-cc6a0.firebasestorage.app',
  );
}
